version: '3.9'
#run: docker compose -f docker-compose.test.yml up -d
name: ticket-booking-test
services:
  redis-test:
    image: redis:7-alpine
    container_name: redis-test
    ports:
      - "6379:6379"

  postgres-test:
    image: postgres:15-alpine
    container_name: postgres-test
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: testdb
      POSTGRES_USER: test