server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ticker_booking
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration

  cache:
    type: redis
  redis:
    url: redis://localhost:6379

  rabbitmq:
    addresses: amqp://guest:guest@localhost:5672

  config:
    import: vault://
  cloud:
    vault:
      uri: http://127.0.0.1:8200
      token: root
      kv:
        backend: secret
        default-context: application

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    prometheus:
      enabled: true

app:
  time:
    expiryTime: 3600

key:
  jwt:
    value: ${vault.key.jwt}

custom-cache:
  default-ttl: 300
  ttls:
    eventDetail: 1800
    userProfile: 3600
    dashboardStats: 10

vnp:
  expire: 60
  payUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  returnUrl: http://localhost:8080/api/payments/vnpay/return
  tmnCode: 3L9OJNZI
  secretKey: ${vault.key.vnp}
  feBackUrl: http://localhost:8888/home


logging:
  level:
    org.springframework.vault: DEBUG
