server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ticker_booking
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate

  cache:
    type: redis
  redis:
    url: redis://localhost:6379

  rabbitmq:
    addresses: amqp://guest:guest@localhost:5672

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    prometheus:
      enabled: true

app:
  time:
    expiryTime: 3600

key:
  jwt:
    value: ${KEY_JWT:12345678901234567890123456789012}

custom-cache:
  default-ttl: 300
  ttls:
    eventDetail: 1800
    userProfile: 3600
    dashboardStats: 10


