server:
  port: 8080
  servlet:
    context-path: /api


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ticker_booking
    username: root
    password: root

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    prometheus:
      enabled: true


  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true


app:
  time:
    expiryTime: 3600

key:
  jwt:
    value: ${KEY_JWT:12345678901234567890123456789012}

